CREATE TABLE IF NOT EXISTS user(
	user_id INT AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(64) NOT NULL,
	picture VARCHAR(64) NOT NULL,
	email VARCHAR(64) NOT NULL, 
	password VARCHAR(64) NOT NULL,
	user_status BOOLEAN NOT NULL,
	last_login BIGINT NOT NULL,
	reservation_status TINYINT NOT NULL,
	account INT NOT NULL,
	gender VARCHAR(16) NOT NULL,
	height INT NOT NULL,
	weight INT NOT NULL,
	total_training_hours INT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS employee(
	employee_id INT AUTO_INCREMENT PRIMARY KEY,
	email VARCHAR(64) NOT NULL,
	employee_name VARCHAR(64) NOT NULL,
	position VARCHAR(256) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS manager(
	manager_id INT AUTO_INCREMENT PRIMARY KEY,
	email VARCHAR(64) NOT NULL,
	manager_name VARCHAR(64) NOT NULL,
	position VARCHAR(256) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS reservation(
	reservation_id INT AUTO_INCREMENT PRIMARY KEY,
	user_id INT NOT NULL,
	activity_id INT NOT NULL,
	reservation_start_time BIGINT NOT NULL,
	reservation_end_time BIGINT NOT NULL,
	venue_id INT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS activity(
	activity_id INT AUTO_INCREMENT PRIMARY KEY,
	activity_name VARCHAR(64),
	max_venuenumber INT NOT NULL,
	current_venuenumber INT NOT NULL,
	current_status BOOLEAN NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS venue(
	venue_id INT AUTO_INCREMENT PRIMARY KEY,
	activity_id INT NOT NULL,
	available BOOLEAN NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
