CREATE TABLE IF NOT EXISTS User(
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	account VARCHAR(127) NOT NULL,
	password VARCHAR(127) NOT NULL,
	display VARCHAR(127) NOT NULL,
	height INT UNSIGNED NOT NULL,
	weight INT UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;