CREATE TABLE IF NOT EXISTS SportRecord(
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	userId INT UNSIGNED NOT NULL,
	sportSiteId INT UNSIGNED NOT NULL,
	roomId INT UNSIGNED NOT NULL,
	seatId INT UNSIGNED NOT NULL,
	date BIGINT UNSIGNED NOT NULL,
	duration BIGINT UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS MonthlyRecord(
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	userId INT UNSIGNED NOT NULL,
	month INT UNSIGNED NOT NULL,
	swimHours INT UNSIGNED NOT NULL,
	squashHours INT UNSIGNED NOT NULL,
	fitnessHours INT UNSIGNED NOT NULL,
	totalHours INT UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Reservation(
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	userId INT UNSIGNED NOT NULL,
	sportSiteId INT UNSIGNED NOT NULL,
	roomId INT UNSIGNED NOT NULL,
	seatId INT UNSIGNED NOT NULL,
	date BIGINT UNSIGNED NOT NULL,
	duration BIGINT UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Sport(
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(127) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS SportSite(
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(127) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Room(
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	sportSiteId INT UNSIGNED NOT NULL,
	name VARCHAR(127) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Seat(
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	roomId INT UNSIGNED NOT NULL,
	name VARCHAR(127) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;