DROP TABLE user, record, employee, manager, reservation, activity, venue;

CREATE TABLE employee(
	id INT AUTO_INCREMENT PRIMARY KEY,
	user_id INT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE invitation_code(
	id INT AUTO_INCREMENT PRIMARY KEY,
	code VARCHAR(256) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE manager(
	id INT AUTO_INCREMENT PRIMARY KEY,
	user_id INT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE reservable(
	id INT AUTO_INCREMENT PRIMARY KEY,
	venue_id INT NOT NULL,
	display_name VARCHAR(64) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE reservation(
	id INT AUTO_INCREMENT PRIMARY KEY,
	user_id INT NOT NULL,
	venue_id INT NOT NULL,
	make_time BIGINT NOT NULL,
	start_time BIGINT NOT NULL,
	duration INT NOT NULL,
	cost DOUBLE NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE time_block(
	id INT AUTO_INCREMENT PRIMARY KEY,
	venue_id INT NOT NULL,
	type INT NOT NULL,
	start_time INT NOT NULL,
	duration INT NOT NULL,
	fee DOUBLE NOT NULL,
	vip_fee DOUBLE NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE user(
	id INT AUTO_INCREMENT PRIMARY KEY,
	email VARCHAR(64) UNIQUE NOT NULL,
	password VARCHAR(64) NOT NULL,
	display_name VARCHAR(64) NOT NULL,
	icon VARCHAR(256) NOT NULL,
	last_login BIGINT NOT NULL,
	amount DOUBLE NOT NULL,
	gender INT NOT NULL,
	height INT NOT NULL,
	weight INT NOT NULL,
	register_time BIGINT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE venue(
	id INT AUTO_INCREMENT PRIMARY KEY,
	display_name VARCHAR(64) NOT NULL,
	icon VARCHAR(256) NOT NULL,
	fee DOUBLE NOT NULL,
	vip_fee DOUBLE NOT NULL,
	location VARCHAR(256) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE venue_comment(
	id INT AUTO_INCREMENT PRIMARY KEY,
	user_id INT NOT NULL,
	venue_id INT NOT NULL,
	post_time BIGINT NOT NULL,
	comment VARCHAR(64) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
