CREATE TABLE topup_record(
	id INT AUTO_INCREMENT PRIMARY KEY,
	user_id INT NOT NULL,
	make_time BIGINT NOT NULL,
	amount DOUBLE NOT NULL,
	paid DOUBLE NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE venue ADD manager_id INT NOT NULL DEFAULT 1 AFTER id;
ALTER TABLE employee ADD manager_id INT NOT NULL DEFAULT 1 AFTER user_id;
ALTER TABLE invitation_code ADD manager_id INT NOT NULL DEFAULT 1 AFTER code;