CREATE TABLE topup_record(
	id INT AUTO_INCREMENT PRIMARY KEY,
	user_id INT NOT NULL,
	make_time BIGINT NOT NULL,
	amount DOUBLE NOT NULL,
	paid DOUBLE NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;